### ISSUE TITLE
unable to find library

### ISSUE THREAD

**Issue by karteekthati** [rommansabbir/NetworkX#10]
I am getting below error

Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.github.rommansabbir:NetworkX:3.3.0.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/github/rommansabbir/NetworkX/3.3.0/NetworkX-3.3.0.pom
       - https://repo.maven.apache.org/maven2/com/github/rommansabbir/NetworkX/3.3.0/NetworkX-3.3.0.pom
       - https://jcenter.bintray.com/com/github/rommansabbir/NetworkX/3.3.0/NetworkX-3.3.0.pom
     Required by:
         project :app

**Comment by rommansabbir** [comment]
Make sure you have set to
````
app level gradle:
compileSdkVersion 31
targetSdkVersion 31

project level gradle:
classpath 'com.android.tools.build:gradle:7.0.3'
````
NetworkX use latest gradle & compile-target sdk

**Comment by karteekthati** [comment]
Hi rommansabbir

my gradle and sdk versions are as below
 classpath "com.android.tools.build:gradle:7.0.3"
      targetSdk 31
    compileSdk 31

**Comment by rommansabbir** [comment]
Make sure you have added the blow depdency in project level gradle.build

`maven { url 'https://jitpack.io' }`

**Comment by karteekthati** [comment]
Thank you after add maven in setting gradle issue resolved.
