### ISSUE TITLE
NetworkX observation isCanceled() method

### ISSUE THREAD

**Issue by mykolapuliaiev** [rommansabbir/NetworkX#6]
Please, add `isCanceled()` method to have ability to check if I need to restart the observation. For now I'm using `try/catch` block to understand if I need to restart observation, but it would be better if there will be a proper way to check.

**Comment by rommansabbir** [comment]
Sure. I will add this feature

**Comment by rommansabbir** [comment]
@nikolaypuliaev Another version has been release. Update to the latest version. Good luck!
