### ISSUE TITLE
Description of  NetworkXObservingStrategy

### ISSUE THREAD

**Issue by mykolapuliaiev** [rommansabbir/NetworkX#7]
Please, describe `NetworkXObservingStrategy` variants more in details. Current naming can't give the idea of how often network will be checked.

**Comment by rommansabbir** [comment]
private val STRATEGY_LOW: Long = 15 * 1000
    private val STRATEGY_MEDIUM: Long = 10 * 1000
    private val STRATEGY_HIGH: Long = 3 * 1000
    private val STRATEGY_REALTIME: Long = 1 * 1000

**Comment by mykolapuliaiev** [comment]
Can you add this to documentation?

**Comment by rommansabbir** [comment]
Updated. Cheers!
